GamesStore2/GamesStore2/Models/BaseEntity.cs
namespace GamesStore2.Models
{
    public class BaseEntity
    {
        public int Id { get; set; }
        public DateTime CreatedAt { get; set; }
        public DateTime UpdatedAt { get; set; }
        public DateTime DeletedAt { get; set; }

    }
}

GamesStore2/GamesStore2/Models/Games.cs
using System.ComponentModel.DataAnnotations.Schema;

namespace GamesStore2.Models
{
    public class Games
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public int Price {  get; set; }
        public string? GameImageUrl { get; set; }
        public string GameId { get; set; }
        [NotMapped]
        public IFormFile? GamesPhoto { get; set; }
        public ICollection<Reviews> Reviews { get; set; }

      

    }
}

GamesStore2/GamesStore2/Models/Reviews.cs
namespace GamesStore2.Models
{
    public class Reviews:BaseEntity
    {
        public int Id { get; set; }

        public string Description { get; set; }
        public int GameId { get; set; }
        public Games? games { get; set; }
        
    }
}

GamesStore2/GamesStore2/ViewModels/HomeVm.cs
namespace GamesStore2.ViewModels
{
    public class HomeVm
    {
    }
}

GamesStore2/GamesStore2/Areas/admin/Controllers/DashBoardController.cs
using Microsoft.AspNetCore.Mvc;

namespace GamesStore2.Areas.admin.Controllers
{
    [Area("admin")]
    public class DashBoardController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

GamesStore2/GamesStore2/Areas/admin/Controllers/GamesController.cs
using GamesStore2.Contexts;
using GamesStore2.Models;
using GamesStore2.Utilities;
using Microsoft.AspNetCore.Mvc;

namespace GamesStore2.Areas.admin.Controllers
{
    [Area("admin")]
    public class GamesController : Controller
    {
        private readonly GameStoreDbContext _context;
        private readonly IWebHostEnvironment _enviroment;

        public GamesController(GameStoreDbContext context,IWebHostEnvironment environment)
        {
            _context = context;
            _enviroment = environment;
        }
        public IActionResult Index()
        {
            var AllGames = _context.games.ToList();
            return View(AllGames);
        }
        public IActionResult Info(int id)
        {
            var gamesinfo=_context.games.Find(id);
            return View(gamesinfo);
        }
        public IActionResult Create()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Create(Games games)
        {
            if (games.GamesPhoto != null)
            {

                if (games.GamesPhoto.Checktype() && games.GamesPhoto.CheckSize(5)) 
                {
                    
                    string fileName = games.GamesPhoto.UploadImage(_enviroment.WebRootPath, @"/Uploads/GamesPhoto/");

                    
                    games.GameImageUrl = @"/Uploads/GamesPhoto/" + fileName;
                }
                else
                {
                   
                    ModelState.AddModelError("GamesPhoto", "Size or Type doesnt true");
                    return View(games);
                }
            }
         
            _context.games.Add(games);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Update()
        {
            
            return View();
        }
        [HttpPost]
        public IActionResult Update(Games games)

        {
            if (ModelState.IsValid)
            {
                Games? updatedGames = _context.games.Find(games.Id);
                if (games == null) { return NotFound(); }
                updatedGames.Id=games.Id;
                updatedGames.Name=games.Name;
                updatedGames.Description=games.Description;
                updatedGames.Price=games.Price;
                updatedGames.GameId = games.GameId;
                updatedGames.GameImageUrl = games.GameImageUrl;
                if (games.GamesPhoto != null)
                {
                   
                    if (games.GamesPhoto.Checktype() && games.GamesPhoto.CheckSize(5))
                    {
                        
                        string fileName = games.GamesPhoto.UploadImage(_enviroment.WebRootPath, @"/Uploads/GamesPhoto/");
                        updatedGames.GameImageUrl = @"/Uploads/GamesPhoto/" + fileName;
                    }
                    else
                    {
                        ModelState.AddModelError("GamesPhoto", "Size or Type is not correct.");
                        return View(games);  
                    }
                    
                    _context.games.Update(updatedGames);
                _context.SaveChanges();
                return RedirectToAction("Index");
                }

            }
            return View(games);
        }
        public IActionResult Delete(int Id)
        {
            Games? deletedgames = _context.games.Find(Id);
            if (deletedgames == null) { return NotFound(); }
            else
            {
                _context.games.Remove(deletedgames);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }

    }
}

GamesStore2/GamesStore2/Areas/admin/Controllers/ReviewsController.cs
using GamesStore2.Contexts;
using GamesStore2.Models;
using Microsoft.AspNetCore.Mvc;

namespace GamesStore2.Areas.admin.Controllers
{
    [Area("admin")]
    public class ReviewsController : Controller
    {
        private readonly GameStoreDbContext _context;


        public ReviewsController(GameStoreDbContext context)
        {
            _context = context;

        }
        public IActionResult Index()
        {
            var AllReviews = _context.reviews.ToList();
            return View(AllReviews);
        }
        public IActionResult Info(int id)
        {
            var reviewsinfo = _context.reviews.Find(id);
            return View(reviewsinfo);
        }
        public IActionResult Create()
        {
            ViewBag.Games = _context.games;
            return View();
        }
        [HttpPost]
        public IActionResult Create(Reviews reviews)
        {
            ViewBag.Games = _context.games;
            _context.reviews.Add(reviews);
            _context.SaveChanges();
            return RedirectToAction("Index");
        }
        public IActionResult Update()
        {
            ViewBag.Games = _context.games;
            return View();
        }
        [HttpPost]
        public IActionResult Update(Reviews reviews)

        {
            if (ModelState.IsValid)
            {
                Reviews? updatedreviews = _context.reviews.Find(reviews.Id);
                if (updatedreviews == null) { return NotFound(); }
                updatedreviews.Id = reviews.Id;
                updatedreviews.Description = reviews.Description;
                updatedreviews.GameId = reviews.GameId;

                ViewBag.Games = _context.games;
                _context.reviews.Update(updatedreviews);
                _context.SaveChanges();
                return RedirectToAction("Index");
            }


            return View(reviews);
        }
        public IActionResult Delete(int Id)
        {
            Reviews? deledetreviews = _context.reviews.Find(Id);
            if (deledetreviews == null) { return NotFound(); }
            else
            {
                _context.reviews.Remove(deledetreviews);
                _context.SaveChanges();
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

GamesStore2/GamesStore2/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;

namespace GamesStore2.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        public IActionResult ProductDetails()
        {
            return View();
        }
        public IActionResult Message()
        {
            return View();
        }
    }
}

GamesStore2/GamesStore2/Areas/admin/Views/Games/Create.cshtml
@model Games

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input class="form-control" asp-for="Price">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GameId"></label>
        <input class="form-control" asp-for="GameId">
        <span asp-validation-for="GameId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GamesPhoto" class="control-label"></label>
        <input class="form-control" asp-for="GamesPhoto" type="file" >
        <span asp-validation-for="GamesPhoto" class="text-danger"></span>
    </div>

    <button type="submit" class="btn btn-primary">Submit</button>
</form>
    

GamesStore2/GamesStore2/Areas/admin/Views/Games/Index.cshtml
@model IEnumerable<Games>

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
                                                                   href="https://datatables.net">official DataTables documentation</a>.
    </p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <a type="button" class="btn btn-primary" mb-3 asp-area="admin" asp-controller="Games" asp-action="Create"> Create </a>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>
                            
                            <th>Id</th>
                            <th>Game Name</th>
                            <th>Game Description</th>
                            <th>Game Price</th>
                            <th>Game Id</th>
                            <th>Game Image </th>
                            
                            

                        </tr>
                    </thead>

                    <tbody>
                        @foreach (Games item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Name</td>
                                <td>@item.Description</td>
                                <td>@item.Price</td>
                                <td>@item.GameId</td>
                                <td><img height="60px" width="auto" src="@item.GameImageUrl" alt="..."></td>
                                
                                <td><a class="btn btn-primary" asp-area="Admin" asp-controller="Games" asp-action="Update" asp-route-id="@item.Id">Update</a></td>
                                <td><a class="btn btn-success" asp-area="Admin" asp-controller="Games" asp-action="Info" asp-route-id="@item.Id">Info</a></td>
                                <td><a class="btn btn-danger" asp-area="Admin" asp-controller="Games" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>

                            </tr>

                        } 

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

GamesStore2/GamesStore2/Areas/admin/Views/Games/Info.cshtml
@model Games
<div class="main-panel">
    <div class="content-wrapper">
        <div class="row">

            <div class="col-lg-12 grid-margin stretch-card">
                <div class="card">
                    <div class="card-body">
                        <h4 class="card-title">Games Table</h4>
                        <p class="card-description">
                            <a class="btn btn-primary mr-2" asp-action="Index">Go Back</a>
                            <a class="btn btn-warning mr-2" style="color:#fff;" asp-action="Update" asp-route-id="@Model.Id">Update</a>
                            <a class="btn btn-danger mr-2 asp-action="Delete" asp-route-id="@Model.Id">Delete</a>
                        </p>
                        <div class="table-responsive">
                            <table class="table table-striped">
                                <thead>
                                    <tr>
                                        <th>Id</th>
                                        <th>Game Name</th>
                                        <th>Game Description</th>
                                        <th>Game Price</th>
                                        <th>Game Id</th>
                                        <th>Game Image </th>
                                        

                                    </tr>
                                </thead>
                                <tbody>

                                    <tr>

                                      
                                        <td>@Model.Id</td>
                                        <td>@Model.Name</td>
                                        <td>@Model.Description</td>
                                        <td>@Model.Price</td>
                                        <td>@Model.GameId</td>
                                        <td><img height="60px" width="auto" src="@Model.GameImageUrl" alt="..."></td>
                                        



                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GamesStore2/GamesStore2/Areas/admin/Views/Games/Update.cshtml
@model Games

<form method="post" enctype="multipart/form-data">
    <div class="form-group">
        <label asp-for="Name"></label>
        <input class="form-control" asp-for="Name">
        <span asp-validation-for="Name" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="Price"></label>
        <input class="form-control" asp-for="Price">
        <span asp-validation-for="Price" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GameId"></label>
        <input class="form-control" asp-for="GameId">
        <span asp-validation-for="GameId" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label asp-for="GamesPhoto" class="control-label"></label>
        <input class="form-control" asp-for="GamesPhoto" type="file" multiple>
        <span asp-validation-for="GamesPhoto" class="text-danger"></span>
    </div>
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

GamesStore2/GamesStore2/Areas/admin/Views/Reviews/Create.cshtml
@model Reviews

<form method="post" enctype="multipart/form-data">
   
    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <label for="GameId">game</label></<br />
    <select class="form-select" asp-for="GameId" asp-items="new SelectList(ViewBag.Games,nameof(Games.Id),nameof(Games.Name))">
        <option selected>Choose Game</option>
    </select>
    <br />
   

    <button type="submit" class="btn btn-primary">Submit</button>
</form>

GamesStore2/GamesStore2/Areas/admin/Views/Reviews/Index.cshtml
@model IEnumerable<Reviews>

<div class="container-fluid">

    <!-- Page Heading -->
    <h1 class="h3 mb-2 text-gray-800">Tables</h1>
    <p class="mb-4">
        DataTables is a third party plugin that is used to generate the demo table below.
        For more information about DataTables, please visit the <a target="_blank"
                                                                   href="https://datatables.net">official DataTables documentation</a>.
    </p>

    <!-- DataTales Example -->
    <div class="card shadow mb-4">
        <div class="card-header py-3">
            <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
            <div class="table-responsive">
                <a type="button" class="btn btn-primary" mb-3 asp-area="admin" asp-controller="Reviews" asp-action="Create"> Create </a>
                <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
                    <thead>
                        <tr>

                            <th>Id</th>
                            <th>Review Description</th>
                            <th>GameId</th>
                           


                        </tr>
                    </thead>

                    <tbody>
                        @foreach (Reviews item in Model)
                        {
                            <tr>
                                <td>@item.Id</td>
                                <td>@item.Description</td>
                                <td>
                                    @item.GameId
                                </td>
                               

                                <td><a class="btn btn-primary" asp-area="Admin" asp-controller="Reviews" asp-action="Update" asp-route-id="@item.Id">Update</a></td>
                                <td><a class="btn btn-success" asp-area="Admin" asp-controller="Reviews" asp-action="Info" asp-route-id="@item.Id">Info</a></td>
                                <td><a class="btn btn-danger" asp-area="Admin" asp-controller="Reviews" asp-action="Delete" asp-route-id="@item.Id">Delete</a></td>

                            </tr>

                        }

                    </tbody>
                </table>
            </div>
        </div>
    </div>

</div>
<!-- /.container-fluid -->

GamesStore2/GamesStore2/Areas/admin/Views/Reviews/Update.cshtml
@model Reviews

<form method="post" enctype="multipart/form-data">

    <div class="form-group">
        <label asp-for="Description"></label>
        <input class="form-control" asp-for="Description">
        <span asp-validation-for="Description" class="text-danger"></span>
    </div>
    <label for="GameId">Game</label></<br />
    <select class="form-select" asp-for="GameId" asp-items="new SelectList(ViewBag.Games,nameof(Games.Id),nameof(Games.Name))">
        <option selected>Choose Game</option>
    </select>
    <br />
    <button type="submit" class="btn btn-primary">Submit</button>
</form>

GamesStore2/GamesStore2/Views/Home/ProductDetails.cshtml
@model IEnumerable<Reviews>
<div class="page-heading header-text">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <h3>Modern Warfare® II</h3>
                <span class="breadcrumb"><a href="#">Home</a>  >  <a href="#">Shop</a>  >  Assasin Creed</span>
            </div>
        </div>
    </div>
</div>

<div class="single-product section">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="left-image">
                    <img src="assets/images/single-game.jpg" alt="">
                </div>
            </div>
            <div class="col-lg-6 align-self-center">
                <h4>Call of Duty®: Modern Warfare® II</h4>
                <span class="price"><em>$28</em> $22</span>
                <p>LUGX Gaming Template is based on the latest Bootstrap 5 CSS framework. This template is provided by TemplateMo and it is suitable for your gaming shop ecommerce websites. Feel free to use this for any purpose. Thank you.</p>
                <form id="qty" action="#">
                    <input type="qty" class="form-control" id="1" aria-describedby="quantity" placeholder="1">
                    <button type="submit"><i class="fa fa-shopping-bag"></i> ADD TO CART</button>
                </form>
                <ul>
                    <li><span>Game ID:</span> COD MMII</li>
                    <li><span>Genre:</span> <a href="#">Action</a>, <a href="#">Team</a>, <a href="#">Single</a></li>
                    <li><span>Multi-tags:</span> <a href="#">War</a>, <a href="#">Battle</a>, <a href="#">Royal</a></li>
                </ul>
            </div>
            <div class="col-lg-12">
                <div class="sep"></div>
            </div>
        </div>
    </div>
</div>

                
 <div class="col-lg-12">
                <form  asp-controller="Reviews"  asp-action="Create" method="post">
                  <div class="row">
                   
                    <div class="col-lg-12">
                      <fieldset>
                        <textarea name="message" id="message" placeholder="Your Message"></textarea>
                      </fieldset>
                    </div>
                    <div class="col-lg-12">
                      <fieldset>
                        <button type="submit" id="form-submit" class="orange-button">Send Message Now</button>
                      </fieldset>
                    </div>
                  </div>
                </form>
            

<div class="more-info">
    <div class="container">
        <div class="row">
            <div class="col-lg-12">
                <div class="tabs-content">
                    <div class="row">
                        <div class="nav-wrapper ">
                            <ul class="nav nav-tabs" role="tablist">
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link active" id="description-tab" data-bs-toggle="tab" data-bs-target="#description" type="button" role="tab" aria-controls="description" aria-selected="true">Description</button>
                                </li>
                                <li class="nav-item" role="presentation">
                                    <button class="nav-link" id="reviews-tab" data-bs-toggle="tab" data-bs-target="#reviews" type="button" role="tab" aria-controls="reviews" aria-selected="false">Reviews (3)</button>
                                </li>
                            </ul>
                        </div>
                        <div class="tab-content" id="myTabContent">
                            <div class="tab-pane fade show active" id="description" role="tabpanel" aria-labelledby="description-tab">
                                <p>You can search for more templates on Google Search using keywords such as "templatemo digital marketing", "templatemo one-page", "templatemo gallery", etc. Please tell your friends about our website. If you need a variety of HTML templates, you may visit Tooplate and Too CSS websites.</p>
                                <br>
                                <p>Coloring book air plant shabby chic, crucifix normcore raclette cred swag artisan activated charcoal. PBR&B fanny pack pok pok gentrify truffaut kitsch helvetica jean shorts edison bulb poutine next level humblebrag la croix adaptogen. Hashtag poke literally locavore, beard marfa kogi bruh artisan succulents seitan tonx waistcoat chambray taxidermy. Same cred meggings 3 wolf moon lomo irony cray hell of bitters asymmetrical gluten-free art party raw denim chillwave tousled try-hard succulents street art.</p>
                            </div>
                            <div class="tab-pane fade" id="reviews" role="tabpanel" aria-labelledby="reviews-tab">
                                <p>Coloring book air plant shabby chic, crucifix normcore raclette cred swag artisan activated charcoal. PBR&B fanny pack pok pok gentrify truffaut kitsch helvetica jean shorts edison bulb poutine next level humblebrag la croix adaptogen. <br><br>Hashtag poke literally locavore, beard marfa kogi bruh artisan succulents seitan tonx waistcoat chambray taxidermy. Same cred meggings 3 wolf moon lomo irony cray hell of bitters asymmetrical gluten-free art party raw denim chillwave tousled try-hard succulents street art.</p>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<div class="section categories related-games">
    <div class="container">
        <div class="row">
            <div class="col-lg-6">
                <div class="section-heading">
                    <h6>Action</h6>
                    <h2>Related Games</h2>
                </div>
            </div>
            <div class="col-lg-6">
                <div class="main-button">
                    <a href="shop.html">View All</a>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="assets/images/categories-01.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="assets/images/categories-05.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="assets/images/categories-03.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="assets/images/categories-04.jpg" alt=""></a>
                    </div>
                </div>
            </div>
            <div class="col-lg col-sm-6 col-xs-12">
                <div class="item">
                    <h4>Action</h4>
                    <div class="thumb">
                        <a href="product-details.html"><img src="assets/images/categories-05.jpg" alt=""></a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

GamesStore2/GamesStore2/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">

<head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <title>Lugx Gaming Shop HTML5 Template</title>

    <!-- Bootstrap core CSS -->
    <link href="~/assets/vendor/bootstrap/css/bootstrap.min.css" rel="stylesheet">


    <!-- Additional CSS Files -->
    <link rel="stylesheet" href="~/assets/css/fontawesome.css">
    <link rel="stylesheet" href="~/assets/css/templatemo-lugx-gaming.css">
    <link rel="stylesheet" href="~/assets/css/owl.css">
    <link rel="stylesheet" href="~/assets/css/animate.css">
    <link rel="stylesheet" href="https://unpkg.com/swiper@7/swiper-bundle.min.css" />
    <!--

    TemplateMo 589 lugx gaming

    https://templatemo.com/tm-589-lugx-gaming

    -->
</head>

<body>

    <!-- ***** Preloader Start ***** -->
    <div id="~/assets/js-preloader" class="~/assets/js-preloader">
        <div class="preloader-inner">
            <span class="dot"></span>
            <div class="dots">
                <span></span>
                <span></span>
                <span></span>
            </div>
        </div>
    </div>
    <!-- ***** Preloader End ***** -->
    <!-- ***** Header Area Start ***** -->
    <header class="header-area header-sticky">
        <div class="container">
            <div class="row">
                <div class="col-12">
                    <nav class="main-nav">
                        <!-- ***** Logo Start ***** -->
                        <a href="index.html" class="logo">
                            <img src="~/assets/images/logo.png" alt="" style="width: 158px;">
                        </a>
                        <!-- ***** Logo End ***** -->
                        <!-- ***** Menu Start ***** -->
                        <ul class="nav">
                            <li><a href="index.html" class="active">Home</a></li>
                            <li><a href="shop.html">Our Shop</a></li>
                            <li><a asp-action="ProductDetails" asp-controller="Home">Product Details</a></li>
                            <li><a href="contact.html">Contact Us</a></li>
                            <li><a asp-area="admin" asp-controller="DashBoard" asp-action="Index">Admin</a></li>
                            <li><a href="#">Sign In</a></li>
                        </ul>
                        <a class='menu-trigger'>
                            <span>Menu</span>
                        </a>
                        <!-- ***** Menu End ***** -->
                    </nav>
                </div>
            </div>
        </div>
    </header>
    <!-- ***** Header Area End ***** -->
        @RenderBody()
    <footer>
        <div class="container">
            <div class="col-lg-12">
                <p>Copyright © 2048 LUGX Gaming Company. All rights reserved. &nbsp;&nbsp; <a rel="nofollow" href="https://templatemo.com" target="_blank">Design: TemplateMo</a></p>
            </div>
        </div>
    </footer>

    <!-- Scripts -->
    <!-- Bootstrap core JavaScript -->
    <script src="~/assets/vendor/jquery/jquery.min.~/assets/js"></script>
    <script src="~/assets/vendor/bootstrap/~/assets/js/bootstrap.min.~/assets/js"></script>
    <script src="assets/~/assets/js/isotope.min.~/assets/js"></script>
    <script src="assets/~/assets/js/owl-carousel.~/assets/js"></script>
    <script src="assets/~/assets/js/counter.~/assets/js"></script>
    <script src="assets/~/assets/js/custom.~/assets/js"></script>

</body>
</html>